### ISSUE TITLE
Blocked: Web Chat rendering huge buttons

### ISSUE THREAD

**Issue by JasonSowers** [microsoft/BotFramework-WebChat#1228]
I can provide a repro. The issue seems to be this property is being added to the button `flex: 0 1 100%;`  when I change it to `flex: 0 1 auto;` the issue goes away

relater PR in adaptive cards repo https://github.com/Microsoft/AdaptiveCards/pull/1795/files

Webchat is rendering my signin card like this:
![image](https://user-images.githubusercontent.com/6301037/47387716-070d1780-d6c5-11e8-96d7-8698476c4abe.png)

**Notes** for @corinagum :

`ac-pushButton`

```css
#bot > div > div > div.wc-message-pane > div.wc-message-groups > div > div:nth-child(4) > div.wc-message.wc-message-from-bot > div > div > div > div > div > div > div:nth-child(3) > div:nth-child(1) > div > button: {
  flex-shrink: auto;
}
```
