### ISSUE TITLE
IE11 render issue : botframework-webchat@master 

### ISSUE THREAD

**Issue by Ganeshdino** [microsoft/BotFramework-WebChat#2803]
🚨 The issue tracker is not for implementation questions 🚨

[Question]

**Comment by Ganeshdino** [comment]
I am running BotFramework-WebChat using npm install botframework-webchat@master . Its working with chrome. But in IE11, its not rendering after initial render. when we type text, its getting response from bot and not rendering in the UI.

**Comment by stevkan** [comment]
@Ganeshdino, as demonstrated in ["How to use"](https://github.com/microsoft/BotFramework-WebChat#how-to-use), can you switch over to `@latest` instead of `@master` and give it a try?

`@master` does not reflect the most up-to-date published version.

**Comment by Ganeshdino** [comment]
Thanks  @stevkan. I will try with @latest. 
But I have already tried with CDN link with latest es5 bundle https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js . Its not working with IE11.

**Comment by Ganeshdino** [comment]
I have downloaded the botframework-webchat@latest and executed it. 
IE11 issue is still the same.. No improvement.

![image](https://user-images.githubusercontent.com/39691416/71974165-c8666d00-3236-11ea-92ce-9342acb27281.png)

**Comment by stevkan** [comment]
Apologies, I think I misunderstood your question, to start. This is looking like it is related to the styling of Web Chat on the page. Can you add/replace the following CSS on your page and see how it affects the rendering?

```css
  <style>
    html,
    body {
      height: 100%;
      width: 100%;
    }

    body {
      margin: 0;
      /* background-color: rgb(52, 5, 139); */
    }

    #webchat {
      height: 100%;
      margin-left: 20px;
      float: left;
      width: 50%;
    }

    #webchat>* {
      height: 95%;
      width: 100%;
    }

  </style>
</head>
```
