### ISSUE TITLE
iOS 15 - Safari address bar covers webchat input box

### ISSUE THREAD

**Issue by MikeCardiff** [microsoft/BotFramework-WebChat#4066]
## Screenshots
![image](https://user-images.githubusercontent.com/63668650/135644411-d243d6d8-4562-423c-9a6d-39703394f8c0.png)

## Describe the bug
This is more of an iOS/Safari issue, but though I'd post here as it impacts webchat. It's not just isolated to botframeowrk-webchat though, pretty much anywhere that has an input at the bottom of the page will have an issue.

In the new iOS 15 Safari redesign, if the address bar is shown at the bottom (new default), when a user taps to type into the message box, the URL is shown above the keyboard covering the input box.

If anyone has any suggestions to a fix for this it would be appreciated!

## Steps to reproduce

1. Go to [mock bot](https://microsoft.github.io/BotFramework-WebChat/01.getting-started/a.full-bundle/) on an iPhone running iOS 15 with Safri set to show the address bar at the bottom.
1. Tap to type a message.
1. Input box is covered by the current URL.

## Additional context

The issue can be somewhat mitigated using some hacky CSS to only work on iPhone but it will cause an empty gap where the url would be displayed if a user is not running latest iOS with the address bar at the bottom:
```css
/* iOS 15 fix for address bar floating over message input box */
@supports (-webkit-touch-callout: none) {
    @media screen and (orientation:portrait) {
        .webchat__send-box:focus-within {
            margin-bottom: 50px;
        }
    }
}
```

[Bug]
