### ISSUE TITLE
Adaptive Cards: 100% height is too tall

### ISSUE THREAD

**Issue by fplaten** [Microsoft/BotFramework-WebChat#933]
Since bumping to Adaptive Cards 1.0.0 I had an issue with the display of PromptChoice dialogs. 

The single choice had a height of 100% (see below).
![image](https://user-images.githubusercontent.com/6834102/38624298-096f2510-3da8-11e8-8348-98a7b7204253.png)

I managed to fix it by setting 
```css
.ac-pushButton {
        flex: 0 1 auto !important;
}
```
Just if anyone is struggling with the same problem :)
